### PR TITLE
Delete '*' on line 54 in Colony.py

### PR DESCRIPTION
**Pull request by brianSalk**
Initially when I ran the code I got a syntax error.  I just removed the '*' on line 54 and it fixed the syntax error, but maybe there was supposed to be some variable on the left-hand side of the '*' operator.  After running the code, my simulation looked reasonable.

### CODE REVIEW

**Comment by vladissta** [comment]
Thanks for your interest in my mini-project, however I cannot reproduce the error you are talking about. Moreover, by erasing asterisk I get a bad result. Can you please give more details about the problem? What version of python do you have and do you have the package versions listed in requirements.txt?

**Comment by brianSalk** [comment]
My python version is 3.10.12
I did install all of the requirements.txt in a virtual environment, which
means we have the same versions.
The error I got was:
File "/home/brian/repos/PCeCoS/scripts/Colony.py", line 54
    resource_matrix[*(cell_coords + idxs_to_eat)] -= self.feed_rate
                    ^
SyntaxError: invalid syntax

From what I am seeing in the code, it looks like both `cell_coords` and
`idxs_to_eat` are both numpy arrays and each array is a 2d array.  I will
try unpacking them manually by indexing them (as opposed to doing it with
*) and see if that fixes the problem.

**Comment by brianSalk** [comment]
I unpacked it manually and now it works fine, the colonies grow like they
should.

**Comment by vladissta** [comment]
It is definitely problem of python version:

https://stackoverflow.com/questions/77580216/starred-unpacking-in-subscription-index

I will add requirements about python version in README.md. Thank you!

**Pull request closed without merging**
